### ISSUE TITLE
why not using diffusers pipeline

### ISSUE THREAD

**Issue by jonasdoevenspeck** [lmmx/deforum-stable-diffusion#10]
I'm wondering why you did not use the existing `StableDiffusionImg2ImgPipeline` from https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py to generate the frames?

**Comment by lmmx** [comment]
This was built from the deforum notebook, and doesn’t change its design other than the notebook vs. Python package format
