### ISSUE TITLE
Python definitions error - V 0.5

### ISSUE THREAD

**Issue by arrfonseca** [lmmx/deforum-stable-diffusion#11]
Hello. When running Python Definitions under v05 I get this
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-191981527364>](https://localhost:8080/#) in <module>
     38 import py3d_tools as p3d
     39 
---> 40 from helpers import DepthModel, sampler_fn
     41 from k_diffusion.external import CompVisDenoiser
     42 from ldm.util import instantiate_from_config

4 frames
[/content/MiDaS/midas/backbones/next_vit.py](https://localhost:8080/#) in <module>
      6 from .utils import activations, forward_default, get_activation
      7 
----> 8 file = open("./externals/Next_ViT/classification/nextvit.py", "r")
      9 source_code = file.read().replace(" utils", " externals.Next_ViT.classification.utils")
     10 exec(source_code)

FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'

Any help would be appreciated
Thanks

**Comment by lmmx** [comment]
I think you must be running someone else’s code, this is a Python package version of the v0.1 notebook, which doesn’t have the code you gave above.
