### ISSUE TITLE
Repeatedly check the init_image path when doing a batch generation?

### ISSUE THREAD

**Issue by XieBaoshi** [lmmx/deforum-stable-diffusion#7]
Is there a way to make this script repeatedly check the init_image path when doing batch generation? (I need it to use the previously generated images as inits for img2img in the second batch, each of them in the same order)

**Comment by lmmx** [comment]
Probably, I am not going to be supplying new features, any updates to this library will be to sync with newer versions of the notebook. Closing as won’t fix
