### ISSUE TITLE
package or license

### ISSUE THREAD

**Issue by jonasdoevenspeck** [lmmx/deforum-stable-diffusion#9]
Any plans to make this a package?
Also it would be nice to include a license so people can use the repo while there is no proper package :)

**Comment by lmmx** [comment]
Er 2 questions here,

- licensing: this was an experiment in reproducing the deforum notebook as a locally executable Python program, at the time it was in v0.1, notebooks don’t tend to have licenses attached so I didn’t choose one.
- Python package status: the setup of the external dependencies was tricky as I remember, and I don’t think it leant itself nicely to a proper Python package, so no I don’t think so. If the more recent versions of the notebook have changed then potentially I could.
